-- migration: 0004 sys_job_idempotency
-- author: data-modeler
-- requires: 0001
-- description: (1) sys.job — Asynq-backed job tracking per ux-patterns.md §3.3.
--              (2) sys.idempotency_key — per api-conventions.md §Idempotency.
--              sys.job_run_history (from 0001) remains for historical batch records;
--              sys.job is the new real-time progress table for user-facing long operations.

BEGIN;

-- ====================================================================
-- 1. sys.job — real-time job progress table
-- ====================================================================
-- Tracks all user-initiated async jobs with live progress (0-100),
-- current step description, SSE-streamable via Redis pub/sub + persisted here.
-- Retention: completed/failed jobs kept 90 days (archival job by Asynq cron).

CREATE TABLE sys.job (
    -- Identity
    id                  TEXT        PRIMARY KEY,        -- ULID generated by Go worker
    type                TEXT        NOT NULL,           -- e.g. ECL_CALC_RUN, EIR_REESTIMATION, EXPORT_CSV

    -- Status tracking
    status              TEXT        NOT NULL DEFAULT 'queued',
                                                        -- queued|running|completed|failed|cancelled
    progress            SMALLINT    NOT NULL DEFAULT 0
                            CONSTRAINT ck_job_progress CHECK (progress BETWEEN 0 AND 100),
    current_step        TEXT,                           -- human-readable step description

    -- Payload & result
    payload_jsonb       JSONB       NOT NULL DEFAULT '{}',
    result_jsonb        JSONB,                          -- populated on completed
    error_jsonb         JSONB,                          -- populated on failed: {code, message, traceId}

    -- Timing
    started_at          TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    can_cancel          BOOLEAN     NOT NULL DEFAULT FALSE,

    -- Audit fields (db-conventions.md — audit cols wajib)
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by          UUID        NOT NULL REFERENCES sec.user(id),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by          UUID        NOT NULL REFERENCES sec.user(id),
    deleted_at          TIMESTAMPTZ,
    deleted_by          UUID        REFERENCES sec.user(id),
    row_version         BIGINT      NOT NULL DEFAULT 1,
    tenant_id           TEXT        NOT NULL DEFAULT 'TUGURE',

    CONSTRAINT ck_job_status CHECK (status IN ('queued','running','completed','failed','cancelled'))
);

-- Indexes for common query patterns
CREATE INDEX ix_job_status ON sys.job(status) WHERE deleted_at IS NULL;
CREATE INDEX ix_job_created_by ON sys.job(created_by, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX ix_job_type_status ON sys.job(type, status) WHERE deleted_at IS NULL;
CREATE INDEX ix_job_tenant_created ON sys.job(tenant_id, created_at DESC);
CREATE INDEX ix_job_active ON sys.job(status, created_at DESC)
    WHERE status IN ('queued','running') AND deleted_at IS NULL;

-- Auto-update updated_at trigger
CREATE TRIGGER tg_job_updated_at
    BEFORE UPDATE ON sys.job
    FOR EACH ROW EXECUTE FUNCTION fn_update_updated_at();

-- Row version increment trigger
CREATE OR REPLACE FUNCTION fn_increment_row_version()
RETURNS TRIGGER AS $$
BEGIN
    NEW.row_version = OLD.row_version + 1;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_job_row_version
    BEFORE UPDATE ON sys.job
    FOR EACH ROW EXECUTE FUNCTION fn_increment_row_version();

COMMENT ON TABLE sys.job IS 'Real-time async job progress tracking per ux-patterns.md §3.3. '
    'Status: queued→running→completed|failed|cancelled. '
    'Progress: 0-100. current_step: human-readable. '
    'payload_jsonb: job parameters snapshot. result_jsonb: populated on completed. '
    'Retention: 90 days (archival cron job in Asynq).';

-- ====================================================================
-- 2. sys.idempotency_key — per api-conventions.md §Idempotency
-- ====================================================================
-- TTL: 24 hours. Middleware checks before processing any mutating endpoint.
-- Same key + same payload hash → return original response (IDEMPOTENCY_REPLAY).
-- Same key + different payload hash → 422 IDEMPOTENCY_MISMATCH.

CREATE TABLE sys.idempotency_key (
    key             UUID        PRIMARY KEY,            -- Idempotency-Key header value
    request_hash    BYTEA       NOT NULL,               -- SHA-256 of request method+path+body
    response_json   JSONB       NOT NULL,               -- original response body
    http_status     SMALLINT    NOT NULL,               -- original HTTP status code
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ NOT NULL DEFAULT (now() + INTERVAL '24 hours'),
    user_id         UUID        REFERENCES sec.user(id),-- owner user (for debug/audit)
    endpoint        TEXT        NOT NULL                -- method + path, e.g. POST /api/v1/penempatan
);

-- Expire old keys quickly (partial index for cleanup job)
CREATE INDEX ix_idempotency_expires ON sys.idempotency_key(expires_at)
    WHERE expires_at < now();

-- Lookup by key is PK (already indexed). Secondary lookup for cleanup:
CREATE INDEX ix_idempotency_user ON sys.idempotency_key(user_id, created_at DESC)
    WHERE user_id IS NOT NULL;

COMMENT ON TABLE sys.idempotency_key IS 'Deduplication store for mutating endpoint requests. '
    'TTL=24h. Checked by idempotency middleware before handler execution. '
    'Cleanup: Asynq cron job deletes WHERE expires_at < now() every 15 minutes.';

COMMIT;
