---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: blips-api
  namespace: blips
  labels:
    app.kubernetes.io/name: blips-api
    app.kubernetes.io/component: api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: blips-api
