#!/usr/bin/env bash
# keycloak-get-pubkey.sh — Ambil RSA-2048 public key PEM dari Keycloak realm blips.
#
# Dipakai untuk mengisi JWT_PUBLIC_KEY_PEM di backend environment.
# Jalankan setelah Keycloak healthy: docker compose ... up -d keycloak
#
# Usage:
#   bash scripts/keycloak-get-pubkey.sh [host_port]
#
# Contoh:
#   bash scripts/keycloak-get-pubkey.sh           # default port 8082
#   bash scripts/keycloak-get-pubkey.sh 8090       # custom port
#
# Output:
#   - PEM dicetak ke stdout (untuk dipakai langsung atau di-export)
#   - Disimpan juga ke .env.keycloak.local (gitignored, jangan commit)

set -euo pipefail

KC_PORT="${1:-8082}"
REALM="blips"
KC_URL="http://localhost:${KC_PORT}"
REALM_URL="${KC_URL}/realms/${REALM}"
OUT_FILE=".env.keycloak.local"

echo "Fetching public key from ${REALM_URL} ..."

# Cek Keycloak healthy dulu.
if ! curl -fs "${KC_URL}/health/ready" > /dev/null 2>&1; then
  echo "ERROR: Keycloak belum ready di ${KC_URL}/health/ready"
  echo "       Jalankan: docker compose -f deploy/docker/docker-compose.dev.yml up -d keycloak"
  echo "       Tunggu hingga status healthy lalu coba lagi."
  exit 1
fi

# Ambil public_key dari realm metadata endpoint.
RAW_KEY=$(curl -fs "${REALM_URL}" | python3 -c "import sys,json; print(json.load(sys.stdin)['public_key'])" 2>/dev/null || true)

if [[ -z "${RAW_KEY}" ]]; then
  # Fallback: coba dengan jq jika python3 tidak tersedia.
  RAW_KEY=$(curl -fs "${REALM_URL}" | jq -r '.public_key' 2>/dev/null || true)
fi

if [[ -z "${RAW_KEY}" || "${RAW_KEY}" == "null" ]]; then
  echo "ERROR: Gagal membaca public_key dari ${REALM_URL}"
  echo "       Pastikan realm '${REALM}' sudah ter-import dan Keycloak healthy."
  exit 1
fi

PEM_KEY="-----BEGIN PUBLIC KEY-----
${RAW_KEY}
-----END PUBLIC KEY-----"

echo ""
echo "=== JWT_PUBLIC_KEY_PEM (RSA-2048, realm: ${REALM}) ==="
echo "${PEM_KEY}"
echo "==="
echo ""

# Simpan ke file .env.keycloak.local untuk dipakai docker compose atau .env.
cat > "${OUT_FILE}" <<EOF
# Generated by scripts/keycloak-get-pubkey.sh — DO NOT COMMIT
# Keycloak realm: ${REALM}, port: ${KC_PORT}
# Regenerate: bash scripts/keycloak-get-pubkey.sh ${KC_PORT}
BLIPS_JWT_PUBLIC_KEY_PEM="${PEM_KEY}"
JWT_ISSUER="${REALM_URL}"
EOF

echo "Public key disimpan ke: ${OUT_FILE}"
echo ""
echo "Untuk pakai di docker compose dev:"
echo "  export BLIPS_JWT_PUBLIC_KEY_PEM=\"\$(cat ${OUT_FILE} | grep -A999 'PUBLIC KEY' | head -n-1 | tail -n+1)\""
echo "  docker compose -f deploy/docker/docker-compose.dev.yml up -d backend"
echo ""
echo "Atau source langsung:"
echo "  source ${OUT_FILE}  # lalu restart backend"
